openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0
paths:
  /api/tasks:
    get:
      summary: Get paginated list of tasks
      tags:
        - Tasks
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCollection'

components:
  schemas:
    TaskCollection:
      type: object
      properties:
        success:
          type: boolean
          example: true
        errors:
          type: null
        data:
          type: object
          # Here you may define the schema for the task collection returned
